apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-honeypot.fullname" . }}-prometheus
  labels:
    {{- include "mcp-honeypot.componentFullLabels" (dict "component" "prometheus" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mcp-honeypot.componentLabels" (dict "component" "prometheus" "root" .) | nindent 4 }}
