apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mcp-honeypot.fullname" . }}-jaeger
  labels:
    {{- include "mcp-honeypot.componentFullLabels" (dict "component" "jaeger" "root" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.jaeger.storageClassName }}
  storageClassName: {{ .Values.jaeger.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.jaeger.storage }}
